--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LunarMoon72/IF-this-doesnt-work-i-hate-myself
build-by-default: true
branches:
- main
projects:
  IF-this-doesnt-work-i-hate-myself:
    path: ""
...
